config/routes.rb
TabHaven::Application.routes.draw do
  devise_for :members
  get "users/new"
	root "staticpages#Home"
	match '/about', to: "staticpages#about", via: 'get'
	match '/help', to: "staticpages#help", via: 'get'
	match '/tos', to: "staticpages#tos", via: 'get'
	match '/privacypolicy', to: "staticpages#privacypolicy", via: 'get'
	match '/contact', to: "staticpages#contact", via: 'get'
	match '/updates', to: "staticpages#updates", via: 'get'
	match '/news', to: "staticpages#news", via: 'get'
	match '/reviews', to: "staticpages#reviews", via: 'get'
	match '/interviews', to: "staticpages#interviews", via: 'get'
	match '/columns', to: "staticpages#columns", via: 'get'
	match '/lessons', to: "staticpages#lessons", via: 'get'
	match '/forums', to: "staticpages#forums", via: 'get'
	match '/contests', to: "staticpages#contests", via: 'get'

end

app/models/member.rb
class Member < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
	def About
	end

	def Home
	end

	def Help
	end

	def tos
	end

	def privacypolicy
	end

	def contact
	end

	def updates
	end

	def news
	end

	def reviews
	end

	def interviews
	end

	def columns
	end

	def lessons
	end

	def forums
	end

	def contests
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div class="footer, center">
	<nav>
		<%= link_to 'About', about_path %> |
		<%= link_to 'Contact', contact_path %> |
		<%= link_to 'TOS', tos_path %> |
		<%= link_to 'Privacy_Policy', privacypolicy_path %> |
		<%= link_to 'Help', help_path %> |
	</nav>

</div>

app/views/layouts/_header.html.erb
<header class ="center">	
	<nav>
		<%= link_to 'Updates', updates_path %> |
		<%= link_to 'News', news_path %> |
		<%= link_to 'Reviews', reviews_path %> |
		<%= link_to 'Interviews', interviews_path %> |
		<%= link_to 'Columns', columns_path %> |
		<%= link_to 'Lessons', lessons_path %> |
		<%= link_to 'Forums', forums_path %> |
		<%= link_to 'Contests', contests_path %> |
	</nav>
	<h1 class ="whitelink">| <%= link_to 'TabsHaven', root_path%> |</h1><br>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<div id="container">
<head>
  <title>TabHaven</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "layouts/header" %>


<%= yield %>


</body>

<div class="clearfooter"></div>
</div>
<div id="footer">
<%= render "layouts/footer" %>
</div>
</html>

app/views/staticpages/Home.html.erb
<div class= "leftside">
<% if member_signed_in? %>

<h3>You Have Succesfully Signed In!</h3>
<%= link_to "Sign Out", destroy_member_session_path, :method => :delete %>

<% else %>

<h2 >
	<%= link_to "Sign In", new_member_session_path, :method => :get %> | 
	<%= link_to "Sign up", new_member_registration_path, :method => :get %>
</h2>

<% end %>
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>